FROM node:20-slim

WORKDIR /app
RUN chown node:node /app

COPY --chown=node:node package*.json ./
RUN npm install

COPY --chown=node:node . .

EXPOSE 5173
USER node

CMD ["npm", "run", "dev", "--", "--host"]
