"""create tables

Revision ID: f16fc94d55b9
Revises: 
Create Date: 2026-07-02 08:56:21.701458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f16fc94d55b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('slack_handle', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('buddy_id', sa.UUID(), nullable=True),
    sa.Column('hybrid_preference', sa.String(), nullable=True),
    sa.Column('assigned_desk', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['buddy_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_employees_buddy_id', 'employees', ['buddy_id'], unique=False)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_table('checklist_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('skip_reason', sa.String(), nullable=True),
    sa.Column('blocked_by', sa.UUID(), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['blocked_by'], ['checklist_tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_checklist_tasks_blocked_by', 'checklist_tasks', ['blocked_by'], unique=False)
    op.create_index('idx_checklist_tasks_employee_id', 'checklist_tasks', ['employee_id'], unique=False)
    op.create_table('schedule_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'date', name='uq_schedule_entries_employee_date')
    )
    op.create_index('idx_schedule_entries_date', 'schedule_entries', ['date'], unique=False)
    op.create_index('idx_schedule_entries_employee_id', 'schedule_entries', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_schedule_entries_employee_id', table_name='schedule_entries')
    op.drop_index('idx_schedule_entries_date', table_name='schedule_entries')
    op.drop_table('schedule_entries')
    op.drop_index('idx_checklist_tasks_employee_id', table_name='checklist_tasks')
    op.drop_index('idx_checklist_tasks_blocked_by', table_name='checklist_tasks')
    op.drop_table('checklist_tasks')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index('idx_employees_buddy_id', table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
